version: "3.3"
services:
  postgres:
    image: postgres:17
    container_name: mikoks-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - mikoks-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - mikoks-network

  backend:
    image: mikoks/borsibaar-backend:mikoks
    container_name: mikoks-backend
    ports:
      - "8087:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
      APP_FRONTEND_URL: ${APP_FRONTEND_URL}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - mikoks-network

  frontend:
    image: mikoks/borsibaar-frontend:mikoks
    container_name: mikoks-frontend
    ports:
      - "3007:3000"
    environment:
      BACKEND_URL: http://backend:8080
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - mikoks-network

volumes:
  mikoks-postgres-data:

networks:
  mikoks-network:
    driver: bridge